Portfolio project, first branch, header and headline.
IsmaelMastronardi/Portfolio pull request #1
Opened 2023-05-31 22:47 UTC by IsmaelMastronardi

This pull request is from the first step on the Portfolio project, and contains the header and headline section of the portfolio, and the linters.
It was done following the third template provided by Microverse on the Figma platform. (https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=1-468&t=zTduG54oS8b3QDah-0).

2023-05-31 22:59 UTC, shahadat3669 requested changes
Hi @IsmaelMastronardi , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

<img src="https://media1.giphy.com/media/jmqAUNFXAElgafPK0g/giphy.gif"/>

## Invalid Code Review Request

- You have submitted a project with a branch named `master` instead of the recommended `main` as the base branch. It is important to ensure consistency and align with [best practices](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md) by using the branch name "main". Don't worry, you can easily change the branch name by following the instructions provided in [this document](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request).
- Secondly, please ensure that you update your README file according to the provided [template](https://github.com/microverseinc/readme-template). It is important to have all the sections configured in your README as per the template. The only optional section is the FAQ section, which you may include based on the needs of your project.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-01 05:41 UTC, wayungi reviewed
Hi @IsmaelMastronardi , 
![image](https://user-images.githubusercontent.com/99656687/224543512-ddbefa59-dc68-47c2-b7fe-f55acdacd3eb.png)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ 

- [ ] You have submitted a project that still has instructions in the readme and many sections not yet filled in. Please fill in all of them. optionally you can delete the **FAQs**

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-01 17:26 UTC, algerina requested changes
Hi @IsmaelMastronardi ,

Great job so far! 
However, you still have minor issues to fix.

May I highlight the following: 
- [x] Your project looks awesome👏  ✔️ 
- [x] Your PR is descriptive ✔️ 
- [x] You design looks similar to the chosen template✔️ 


## STATUS: CHANGES REQUIRED ♻️ 
PLEASE: check the comments under the review

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 
 ## Optional suggestions

 - Please check the comment under the review


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2023-06-01 17:26 UTC, algerina commented on index.html
> +        </div>
- [ ] You did well working on that part of the project but it's required to use a `section` instead of a `div`. You can find further informations in the following [link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section).

2023-06-01 17:26 UTC, algerina commented on index.html
> +            </div>
- [ ] For the list of icons it is required to use a `ul `tag to group them, and `li` per icon; each icon has a link (a tag).

Apart from being semantically correct, the a tag will let you connect your social networks with the icons, using href.

2023-06-01 19:41 UTC, OyePriscilla approved these changes
Hi @IsmaelMastronardi 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Used appropriate semantics tag to wrap HTML element ✔️ 
Observed GitHub flow ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 19:41 UTC, OyePriscilla commented on README.md
>  > Describe between 1-3 key features of the application.
- [optional] Kindly remove all the placeholders in your README file, they are there to guide on what to do with each section. 👍

2023-06-01 19:46 UTC, merged